server:
  port: 90

spring:
  profiles:
    active: dev
  #数据库配置
  datasource:
    url: jdbc:mysql://175.24.123.165:3306/cosmetics?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
#    schema: classpath:/sql/schema.sql

  servlet:
    multipart:
      max-file-size: 20MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # sql执行语句打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  type-aliases-package: com.cosmetics.module.user.entity,;
